### ISSUE TITLE
Value not updating on Numeric Input

### ISSUE THREAD

**Issue by varukashotta** [himelbrand/react-native-numeric-input#13]
Hi, thank you for the plugin,

I have a new installation of reeact-native and copied the exact example code in my App,js file but the value does not decrease or increase, could you please help on how best to resolve this ?

**Comment by tanmynguyen** [comment]
I Same :(

**Comment by Mhd-Emad** [comment]
Also, I faced the same issue.

**Comment by adamthewan** [comment]
`componentDidUpdate() {
    if (this.props.initValue !== this.state.value) {
      this.setState({value: this.props.initValue, lastValid: this.props.initValue, stringValue: this.props.initValue.toString()});
    }
  }`

If it helps, commenting out this code fixed the issue for me.

**Comment by varukashotta** [comment]
Works for me, thanks

> ```
> componentDidUpdate() {
>      if (this.props.initValue !== this.state.value) {
>        this.setState({value: this.props.initValue, lastValid: this.props.initValue, stringValue: this.props.initValue.toString()});
>      }
>   }
> 
> If it helps, commenting out this code fixed the issue for me.
> ```

Thanks @adamthewan

**Comment by fnaquira** [comment]
Would it be great if this was added to the official repo

**Comment by himelbrand** [comment]
thank you for finding the issue,
seems it's from the last PR.
it will be fixed soon

**Comment by himelbrand** [comment]
bug was fixed
by changing componentDidUpdate to componentWillReceiveProps
thank you @mattyx96

**Comment by pmairif** [comment]
I'm seeing this issue with v1.6.5 (again?).

**Comment by grypesc** [comment]
The bug is still on and is caused by updating values with initial values instead of new values.  The following solution worked for me: 
Simply replace the following method in _react-native-numeric-input/NumericInput/NumericInput.js_
```
componentWillReceiveProps(props) {
    if (props.initValue !== this.state.value) {
      this.setState({
        value: props.initValue,
        lastValid: props.initValue,
        stringValue: props.initValue.toString()
      });
    }
  }
```

With this:

```
componentWillReceiveProps(props) {
    if (props.initValue !== this.state.value) {
      this.setState({
        value: props.value,
        lastValid: props.value,
        stringValue: props.value.toString()
      });
    }
  }
```

**Comment by Ahmad5448** [comment]
value={item.quantity} 
 initValue={item.quantity}
just pass same values in both it will work 
hope this will work ,
cheers

**Comment by JulianoLoren** [comment]
> ```
> componentDidUpdate() {
>      if (this.props.initValue !== this.state.value) {
>        this.setState({value: this.props.initValue, lastValid: this.props.initValue, stringValue: this.props.initValue.toString()});
>      }
>   }
> 
> If it helps, commenting out this code fixed the issue for me.
> ```

it really helped

**Comment by yunisv** [comment]
This one 
```
componentDidUpdate() {
        const initSent = !(this.props.initValue !== 0 && !this.props.initValue);

        // compare the new value (props.initValue) with the existing/old one (this.state.value)
        if (this.props.initValue !== this.state.value && initSent) {
            this.setState({
                value: this.props.initValue,
                lastValid: this.props.initValue,
                stringValue: this.props.initValue.toString()
            });
        }
    }
```
replaced 
```
componentDidUpdate(prevProps) {
        const initSent = !(this.props.initValue !== 0 && !this.props.initValue);

        if (this.props.initValue !== prevProps.initValue && initSent) {
            // Если initValue изменился, обновляем state
            this.setState({
                value: this.props.initValue,
                lastValid: this.props.initValue,
                stringValue: this.props.initValue.toString()
            });
        }
    }
```
this worked for me ( ver1.9.1 2025 )
